# Generated by Django 5.1 on 2024-08-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nginxlogentry',
            old_name='uri',
            new_name='url',
        ),
    ]
